// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef binary_calculator_h
#define binary_calculator_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Spinner.H>
extern Fl_Spinner *n;
extern Fl_Spinner *bits;
#include <FL/Fl_Input.H>
extern Fl_Input *outputA;
extern Fl_Input *outputB;
extern Fl_Input *outputC;
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#endif
